<?php

return [
    'captcha_enabled' => env('GOOGLE_RECAPTCHA_ENABLED', true),
    'permissions' => [
        'banner-list' => 'Banner list',
        'banner-create' => 'Banner create',
        'banner-update' => 'Banner update',
        'banner-show' => 'Banner show',
        'banner-delete' => 'Banner action',
        'user-list' => 'User list',
        'user-create' => 'User Create',
        'user-update' => 'User Update',
        'user-show' => 'User Show',
        'role-list' => 'Role list',
        'role-show' => 'Role show',
        'role-create' => 'Role Create',
        'role-update' => 'Role Update',
        'customer-list' => 'Customer list',
        'customer-create' => 'Customer Create',
        'customer-update' => 'Customer Update',
        'customer-export' => 'Customer Export',
        'order-list' => 'Order list',
        'order-create' => 'Order Create',
        'order-show' => 'Order Show',
        'order-update' => 'Order Update',
        'order-export' => 'Order Export',
        'dashboard-order-graph' => 'Can show order yearly graph',
        'dashboard-customer-graph' => 'Can show customer yearly graph',
        'dashboard-stats' => 'Can show statistics counter',
        'supplier-list' => 'Can see supplier list',
        'supplier-create' => 'Can create supplier',
        'supplier-show' => 'Can show supplier',
        'supplier-update' => 'Can update supplier',
        'supplier-action' => 'Can action supplier',
        'category-list' => 'Can see category list',
        'category-create' => 'Can create category',
        'category-update' => 'Can update category',
        'category-action' => 'Can action category',
        'product-list' => 'Can see product list',
        'product-create' => 'Can create product',
        'product-update' => 'Can update product',
        'product-action' => 'Can action product',
        'payment-list' => 'Order list',
        'payment-create' => 'Order Create',
        'payment-show' => 'Order Show',
        'payment-update' => 'Order Update',
    ]
];
