<?php

return [
    'captcha_enabled' => env('GOOGLE_RECAPTCHA_ENABLED', true),
    'permissions' => [
        'user-list' => 'User list',
        'user-create' => 'User Create',
        'user-update' => 'User Update',
        'user-show' => 'User Show',
        'role-list' => 'Role list',
        'role-show' => 'Role show',
        'role-create' => 'Role Create',
        'role-update' => 'Role Update',
        'customer-list' => 'Customer list',
        'customer-create' => 'Customer Create',
        'customer-update' => 'Customer Update',
        'customer-export' => 'Customer Export',
        'order-list' => 'Order list',
        'order-create' => 'Order Create',
        'order-show' => 'Order Show',
        'order-update' => 'Order Update',
        'order-export' => 'Order Export',
        'dashboard-order-graph' => 'Can show order yearly graph',
        'dashboard-customer-graph' => 'Can show customer yearly graph',
        'dashboard-stats' => 'Can show statistics counter',
        'feedback-list' => 'Can see feedback list',
        'feedback-create' => 'Can create feedback',
        'feedback-update' => 'Can update feedback',
        'complain-list' => 'Can see complain list',
        'complain-create' => 'Can create complain',
        'complain-update' => 'Can update complain',
        'payment-list' => 'Order list',
        'payment-create' => 'Order Create',
        'payment-show' => 'Order Show',
        'payment-update' => 'Order Update',
    ]
];
